server:
    port: 8800
spring:
    datasource:
        url: jdbc:mysql://192.168.16.34:14314/hawk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: Password
eureka:
    instance:
        hostname: localhost
    client:
        serviceUrl:
            defaultZone: http://localhost:8080/eureka/
hawk:
    project:
        codebase:
            git:
                repoPath: /tmp/repo

