server:
    port: 8805

spring:
    datasource:
        url: jdbc:mysql://192.168.200.24:31975/hawk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: Password

eureka:
    instance:
        hostname: localhost
    client:
        serviceUrl:
            defaultZone: http://localhost:8080/eureka/

hawk:
    kubernetes:
        apiServer: https://192.168.200.24:6443
        token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlFFRHpWb0JLM2NUWkozQ1M1aVJwdEl4bGVsX0FaaEV5bTBfY1A0NkUwVGcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJoYXdrLXRva2VuLTQ2bGdnIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6Imhhd2siLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJhZjk2ZDdhZS04ZDQzLTRiMmEtYTZjZC1jMTBlZGYwZDdjN2UiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06aGF3ayJ9.DajVcwDHRrq9esGiaQDjU30epdpvMK28nF25l7U3Akwl-uKqajYOhHGm4-hE6r0jk-bZRXatVsBZj3MbvBiq4egGL5N5OabdX1vGDA0SzCVA6aOXU8VPtCc8M6lbBhKBXXi_Em2RknpOZW7I3vvYu0kYjPUbkny8qPKy8K51MHR0KsIJHQp2obHSnK0vWLydGsmlywAUo3CmifqjpDgmaGoE03aojc3ygBwQuzMnmzIufq5zLDvh7Ki_OSXFCPiL251b_bIfvzpoIKKX53cMtyJN0ryhZ6EkyOyQPOTjOEf4gt-C1CnzRoToyXL5j8KW_O4In0WIDoUykC3lf7szOQ
