server:
    port: 8700
spring:
    datasource:
        url: jdbc:mysql://192.168.16.34:44881/hawk?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
        username: root
        password: Password
    redis:
        host: 192.168.16.34
        password: Password
        port: 7598
eureka:
    instance:
        hostname: localhost
    client:
        serviceUrl:
            defaultZone: http://localhost:8080/eureka/
