spring:
    application:
        name: traffic
    profiles:
        active: dev
    jpa:
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                query.substitutions: true 1, false 0
                max_fetch_depth: 2
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
                connection.zeroDateTimeBehavior: convertToNull
                enable_lazy_load_no_trans: false
                globally_quoted_identifiers: true


trace:
    header-filter:
        requestKey: ":method,:path,:authority,x-request-id,x-envoy-attempt-count,x-forwarded-proto,:scheme,x-forwarded-client-cert,x-b3-sampled,:authority,x-ot-span-context,x-b3-flags"
        responseKey: "date,x-envoy-peer-metadata,x-envoy-peer-metadata-id,x-envoy-upstream-service-time"
