server:
    port: 8700
spring:
    datasource:
        url: jdbc:mysql://192.168.16.34:14314/hawk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: Password
    redis:
        host: 192.168.24.207
        password: HvWd7CdQyt
        port: 33010
eureka:
    instance:
        hostname: localhost
    client:
        serviceUrl:
            defaultZone: http://localhost:8080/eureka/
