server:
    port: 8700
spring:
    datasource:
        url: jdbc:mysql://192.168.16.34:41123/hawk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: Password
    redis:
        host: 192.168.16.34
        password: Password
        port: 31604
eureka:
    instance:
        hostname: localhost
    client:
        serviceUrl:
            defaultZone: http://localhost:8080/eureka/
