docker:
  enabled: false
  secretName: ""
  dockerConfig: ""

persistent:
  # 是否需要支持存储卷，建议至少使用nfs
  enabled: true
  volume:
    # 为应用保存日志
    - name: hawk-log
      enabled: false
      storageClass: rook-cephfs
      size: 20Gi
      namespace: default
    # hawk构建项目时的本地仓库，支持npm，maven，gradle
    - name: lib-repo
      enabled: true
      # nfs地址
      nfs: 192.168.16.34
      # nfs export path
      path: /app/nfs/repo
      # 需要的存储空间
      size: 30Gi
      namespace: build
# 部署hawk app配置
hawk:
  # hawk 构建应用image前缀，用于表示仓库
  appImagePrefix: registry.cn-qingdao.aliyuncs.com/kangta123
  appns: default
  # hawk app 运行版本
  version: v4.2
  # hawk app 健康检查地址
  readiness: /actuator/health/readiness
  # 访问hawk应用域名，配合ingress 需要支持dns泛解析
  host: hawk.cn
  # hawk app 运行性能级别
  performance: NORMAL
  deps:
    # hawk app 依赖服务版本 @ https://github.com/kangta123/hawk-deps.git
      version: v4.5.5
  build:
    # 构建服务所在命名空间
    namespace: build
  # 每一个module 可以单独指定version
  modules:
  - name: hawk-base
    image: registry.cn-qingdao.aliyuncs.com/kangta123/hawk/hawk_base-core
  - name: hawk-message
    image: registry.cn-qingdao.aliyuncs.com/kangta123/hawk/hawk_message-core
  - name: hawk-project
    image: registry.cn-qingdao.aliyuncs.com/kangta123/hawk/hawk_project-core
  - name: hawk-container
    image: registry.cn-qingdao.aliyuncs.com/kangta123/hawk/hawk_container-core
    version: v4.1.6.1
  - name: hawk-kubernetes
    image: registry.cn-qingdao.aliyuncs.com/kangta123/hawk/hawk_kubernetes-core
    version: v4.1.5.1
  - name: hawk-kubernetes-keepalive
    image: registry.cn-qingdao.aliyuncs.com/kangta123/hawk/hawk_kubernetes-keepalive
  - name: hawk-monitor
    image: registry.cn-qingdao.aliyuncs.com/kangta123/hawk/hawk_monitor-core
  - name: hawk-gateway
    readiness: /actuator/health
    image: registry.cn-qingdao.aliyuncs.com/kangta123/hawk/hawk_gateway
  kubernetes:
    # k8s api server地址
    apiServer: https://10.211.55.6:6443
    # 访问api server认证token
    token: ""
  kafka:
    url: hawk-kafka:9092
    zookeeper:
      persistence:
        enabled: false
  app:
    image: registry.cn-qingdao.aliyuncs.com/kangta123/hawk/hawk_springboot11
  eureka:
    image: registry.cn-beijing.aliyuncs.com/9fbank/onecard-arch_discovery
    version: "1210000"
  # hawk ui
  ui:
    image: registry.cn-qingdao.aliyuncs.com/kangta123/hawk/hawk-ui
    # ui 版本
    version: v4.2
    # ui将api转发到网关模块hawk gateway, gateway地址
    gateway: hawk-gateway:8080

# 数据库配置
mysql:
  initdbScriptsConfigMap: hawk-db
  auth:
    rootPassword: "Password"
    database: "hawk"
  primary:
    persistence:
      enabled: false
      storageClass: "rook-ceph-block"
      size: 50Gi
    service:
      type: "NodePort"
kafka:
  persistence:
    enabled: false
  zookeeper:
    persistence:
      enabled: false

redis:
  cluster:
    enabled: false
  master:
    persistence:
      enabled: false
  slave:
    persistence:
      enabled: false
  password: "Password"

prometheus:
  alertmanager:
    enabled: false
  server:
    retention: "7d"
    persistentVolume:
      enabled: false
      storageClass: rook-ceph-block
      size: 100Gi
  pushgateway:
     enabled: false

ingress-nginx:
  controller:
    hostPort:
      enabled: true
    service:
      nodePorts:
        http: 80
    image:
      repository:  registry.cn-qingdao.aliyuncs.com/kangta123/k8s/ingress-nginx/controller
      digest: ""
    admissionWebhooks:
      patch:
        image:
          repository: registry.cn-qingdao.aliyuncs.com/kangta123/k8s/jettech/kube-webhook-certgen
