apiVersion: v1
data:
  application-prod.yaml: |+
    spring:
      datasource:
        url: jdbc:mysql://hawk-mysql-headless:3306/{{ .Values.mysql.auth.database }}?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
        username: root
        password: {{ .Values.mysql.auth.rootPassword }}
      redis:
        host: hawk-redis-headless
        password: {{ .Values.redis.password }}
      kafka:
        bootstrap-servers: {{ .Values.hawk.kafka.url }}
    eureka:
      client:
        serviceUrl:
          defaultZone: http://default-eureka-server:8080/eureka
    hawk:
      kubernetes:
        apiServer: {{ .Values.hawk.kubernetes.apiServer }}
        token: {{ .Values.hawk.kubernetes.token }}

kind: ConfigMap
metadata:
  name: hawk-kubernetes-keepalive-config

