apiVersion: v1
data:
  application-prod.yaml: |+
    spring:
      datasource:
        url: jdbc:mysql://hawk-mysql-headless:3306/{{ .Values.mysql.auth.database }}?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
        username: root
        password: {{ .Values.mysql.auth.rootPassword }}
      kafka:
        bootstrap-servers: {{ .Values.hawk.kafka.url }}
    eureka:
      client:
        serviceUrl:
          defaultZone: http://default-eureka-server:8080/eureka


kind: ConfigMap
metadata:
  name: hawk-message-config

