{{  with .Values.hawk.ui }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sidecar.istio.io/inject: "false"
  labels:
    server: hawk
  name: hawk-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      component: hawk-ui
  template:
    metadata:
      labels:
        component: hawk-ui
    spec:
      containers:
      - image: {{ .image }}:{{ .version }}
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/local/openresty/nginx/conf/nginx.conf
          name: hawk-ui-config
          subPath: nginx.conf
      volumes:
      - configMap:
          name: configmap-hawk-nginx
        name: hawk-ui-config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: hawk-ui
  name: hawk-ui
spec:
  ports:
  - name: hawk
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    component: hawk-ui

---
apiVersion: v1
data:
  nginx.conf: |2+
        worker_processes  2;

        error_log  /error.log;

        events {
            accept_mutex on;
            multi_accept on;
            use epoll;
            worker_connections  1024;
        }


        http {
            include       mime.types;
            default_type  application/octet-stream;

            log_format  main  '$time_local $remote_user $remote_addr $host $request_uri $request_method '
                              '$status $body_bytes_sent "$http_referer" '
                              '"$http_user_agent" "$http_x_forwarded_for" '
                              '$request_time $upstream_response_time "$upstream_cache_status"';

            log_format  browser '$time_iso8601 $cookie_km_uid $remote_addr $host $request_uri $request_method '
                              '$status $body_bytes_sent "$http_referer" '
                              '"$http_user_agent" "$http_x_forwarded_for" '
                              '$request_time $upstream_response_time "$upstream_cache_status" $http_x_requested_with $http_x_real_ip $upstream_addr $request_body';

            log_format client '{"@timestamp":"$time_iso8601",'
                              '"time_local":"$time_local",'
                              '"remote_user":"$remote_user",'
                              '"http_x_forwarded_for":"$http_x_forwarded_for",'
                              '"host":"$server_addr",'
                              '"remote_addr":"$remote_addr",'
                              '"http_x_real_ip":"$http_x_real_ip",'
                              '"body_bytes_sent":$body_bytes_sent,'
                              '"request_time":$request_time,'
                              '"status":$status,'
                              '"upstream_response_time":"$upstream_response_time",'
                              '"upstream_response_status":"$upstream_status",'
                              '"request":"$request",'
                              '"http_referer":"$http_referer",'
                              '"http_user_agent":"$http_user_agent"}';

            access_log  /access.log  main;
            gzip_static     on;
            sendfile        on;

            keepalive_timeout 120s 100s;
            keepalive_requests 500;
            send_timeout 60000s;
            client_header_buffer_size 4k;
            proxy_ignore_client_abort on;
            proxy_buffers 16 32k;
            proxy_buffer_size 64k;

            proxy_busy_buffers_size 64k;

            proxy_send_timeout 60000;
            proxy_read_timeout 60000;
            proxy_connect_timeout 60000;
            proxy_cache_valid 200 304 2h;
            proxy_cache_valid 500 404 2s;
            proxy_cache_key $host$request_uri$cookie_user;
            proxy_cache_methods GET HEAD POST; proxy_redirect off; proxy_http_version 1.1;
            proxy_set_header Host                $http_host;
            proxy_set_header X-Real-IP           $remote_addr;
            proxy_set_header X-Forwarded-For     $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto   $scheme;
            proxy_set_header X-Frame-Options     SAMEORIGIN;

            server_tokens off;
            client_max_body_size 50G;
            add_header X-Cache $upstream_cache_status;
            autoindex off;

            resolver      127.0.0.1:53 ipv6=off;

            server {
              listen 80;
              gzip on;
              gzip_min_length 1k;
              gzip_comp_level 9;
              gzip_types text/plain text/css text/javascript application/json application/javascript application/x-javascript application/xml;
              gzip_vary on;
              gzip_disable "MSIE [1-6]\.";

              root /usr/local/openresty/nginx/html/;

              location /socket/kubekeepalive/ws {
                    rewrite /socket/(.*) /$1  break;
                    proxy_pass http://{{ .gateway }};

                    proxy_set_header Host $http_host;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection upgrade;
              }
              location /api {
                rewrite /api/(.*) /$1  break;
                proxy_pass http://{{ .gateway }};
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   Host              $http_host;
                proxy_set_header   X-Real-IP         $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              }

              location /sw.js {
                        add_header Cache-Control "no-cache";
                        proxy_cache_bypass $http_pragma;
                        proxy_cache_revalidate on;
                        expires off;
                        access_log off;
                    }

              location / {
                try_files $uri $uri/ /index.html;
              }
            }
       }


kind: ConfigMap
metadata:
  name: configmap-hawk-nginx

{{ end }}
