server:
    port: 8700
spring:
    datasource:
        url: jdbc:mysql://192.168.24.207:27437/hawk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: root
eureka:
    instance:
        hostname: localhost
    client:
        serviceUrl:
            defaultZone: http://eureka-test-one.sk.9f.cn/eureka #http://localhost:8080/eureka/
