server:
  port: 8803

spring:
  datasource:
    url: jdbc:mysql://192.168.16.34:44881/hawk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: Password
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
hawk:
  container:
    default-instance-namespace: default
    domain-host: sk.9f.cn
    build-namespace: build
    app-image-prefix: registry.cn-qingdao.aliyuncs.com/kangta123
    gateway-url: hawk-gateway.hawk:8080
    pvc-log: true
  runtime:
    buildVolume: lib-repo
    config:
      nginx:
        runtime:
          appImage: registry.cn-qingdao.aliyuncs.com/kangta123/hawk_nginx:v2.0-release
          dataImage: registry.cn-qingdao.aliyuncs.com/kangta123/hawk_init_npm:v2.0-release
          podInteractionVolume: /tmp/app:/usr/local/openresty/nginx/html
        build:
          npm:
            image: registry.cn-qingdao.aliyuncs.com/kangta123/hawk_npm_build:v2.0-release
            sub: npm
      tomcat:
        runtime:
          appImage: registry.cn-qingdao.aliyuncs.com/kangta123/hawk_tomcat8:v2.0-release
          dataImage: registry.cn-qingdao.aliyuncs.com/kangta123/hawk_init_tomcat:v2.0-release
          podInteractionVolume: /tmp/app:/usr/local/apache-tomcat-8.5.46/webapps/ROOT
        build:
          npm:
            image: registry.cn-qingdao.aliyuncs.com/kangta123/hawk_maven_build:v2.0-release
            volume:
              sub: maven
              mountPath: /root/.m2/
      springboot:
        runtime:
          appImage: registry.cn-qingdao.aliyuncs.com/kangta123/hawk_springboot8:v2.0-release
          dataImage: registry.cn-qingdao.aliyuncs.com/kangta123/hawk_init_springboot:v2.0-release
          podInteractionVolume: /tmp/app:/app/jar
        build:
          maven:
            image: registry.cn-qingdao.aliyuncs.com/kangta123/hawk_maven_build:v2.0-release
            volume:
              sub: maven
              mountPath: /root/.m2/
          gradle:
            image: registry.cn-qingdao.aliyuncs.com/kangta123/hawk_gradle_build:v2.0-release
            volume:
              sub: gradle
              mountPath: /gradle
