server:
    port: 8803

spring:
    datasource:
        url: jdbc:mysql://192.168.24.207:27437/hawk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
    redis:
        host: 192.168.24.207
        password: HvWd7CdQyt
        port: 33010

eureka:
    instance:
        hostname: localhost
    client:
        serviceUrl:
            defaultZone: http://localhost:8080/eureka/

hawk:
    container:
        default-instance-namespace: default
        domain-host: hawk.cn
        build-namespace: build
        app-image-prefix: "registry.cn-qingdao.aliyuncs.com/kangta123"
        gateway-url: "localhost:8001"
        pvc-log: true
    runtime:
        buildVolume: lib-repo
        config:
            nginx:
                runtime:
                    appImage: registry.cn-qingdao.aliyuncs.com/kangta123/hawk/hawk_nginx:v4.5
                    dataImage: registry.cn-qingdao.aliyuncs.com/kangta123/hawk/hawk_init_npm:v4.5
                    podInteractionVolume: /tmp/app:/usr/local/openresty/nginx/html
                build:
                    npm:
                        image: registry.cn-qingdao.aliyuncs.com/kangta123/hawk/hawk_npm_build:v4.5
                        sub: npm
            tomcat:
                runtime:
                    appImage: registry.cn-qingdao.aliyuncs.com/kangta123/hawk/hawk_tomcat8:v4.5
                    dataImage: registry.cn-qingdao.aliyuncs.com/kangta123/hawk/hawk_init_tomcat:v4.5
                    podInteractionVolume: /tmp/app:/usr/local/apache-tomcat-8.5.46/webapps/ROOT
                build:
                    npm:
                        image: registry.cn-qingdao.aliyuncs.com/kangta123/hawk/hawk_maven_tomcat_build:v4.5
                        volume:
                            volume: maven-repository-nfs
                            sub: maven
            springboot:
                runtime:
                    appImage: registry.cn-qingdao.aliyuncs.com/kangta123/hawk/hawk_springboot8:v4.5
                    dataImage: registry.cn-qingdao.aliyuncs.com/kangta123/hawk/hawk_init_springboot:v4.5
                    podInteractionVolume: /tmp/app:/app/jar
                build:
                    maven:
                        image: registry.cn-qingdao.aliyuncs.com/kangta123/hawk/hawk_maven_springboot_build:v4.5
                        volume:
                            volume: lib-repository
                            sub: maven
                    gradle:
                        image: registry.cn-qingdao.aliyuncs.com/kangta123/hawk/hawk_gradle_build:v4.5
                        volume:
                            volume: gradle-repository-nfs
                            sub: gradle


